// Sample data for the Return Value Recovery Dashboard
window.sampleData = [
    {
        "SKU": "EL-1001",
        "Product Name": "Premium Smartphone",
        "Category": "Electronics",
        "Returned Qty": 1,
        "Condition": "Like New",
        "Refurbishment Cost": 45.00,
        "Resale Value": 499.99,
        "Days in Process": 3,
        "Disposition": ""
    },
    {
        "SKU": "EL-1002",
        "Product Name": "Wireless Headphones",
        "Category": "Electronics",
        "Returned Qty": 1,
        "Condition": "Good",
        "Refurbishment Cost": 12.50,
        "Resale Value": 89.99,
        "Days in Process": 5,
        "Disposition": ""
    },
    {
        "SKU": "EL-1003",
        "Product Name": "Smart Watch",
        "Category": "Electronics",
        "Returned Qty": 1,
        "Condition": "Fair",
        "Refurbishment Cost": 35.00,
        "Resale Value": 129.99,
        "Days in Process": 7,
        "Disposition": ""
    },
    {
        "SKU": "EL-1004",
        "Product Name": "Bluetooth Speaker",
        "Category": "Electronics",
        "Returned Qty": 1,
        "Condition": "Poor",
        "Refurbishment Cost": 28.75,
        "Resale Value": 39.99,
        "Days in Process": 10,
        "Disposition": ""
    },
    {
        "SKU": "EL-1005",
        "Product Name": "Tablet",
        "Category": "Electronics",
        "Returned Qty": 1,
        "Condition": "Like New",
        "Refurbishment Cost": 55.00,
        "Resale Value": 349.99,
        "Days in Process": 4,
        "Disposition": ""
    },
    {
        "SKU": "AP-2001",
        "Product Name": "Designer Jeans",
        "Category": "Apparel",
        "Returned Qty": 1,
        "Condition": "Like New",
        "Refurbishment Cost": 8.50,
        "Resale Value": 79.99,
        "Days in Process": 2,
        "Disposition": ""
    },
    {
        "SKU": "AP-2002",
        "Product Name": "Winter Jacket",
        "Category": "Apparel",
        "Returned Qty": 1,
        "Condition": "Good",
        "Refurbishment Cost": 15.00,
        "Resale Value": 129.99,
        "Days in Process": 6,
        "Disposition": ""
    },
    {
        "SKU": "AP-2003",
        "Product Name": "Running Shoes",
        "Category": "Apparel",
        "Returned Qty": 1,
        "Condition": "Poor",
        "Refurbishment Cost": 18.25,
        "Resale Value": 29.99,
        "Days in Process": 8,
        "Disposition": ""
    },
    {
        "SKU": "AP-2004",
        "Product Name": "Leather Handbag",
        "Category": "Apparel",
        "Returned Qty": 1,
        "Condition": "Fair",
        "Refurbishment Cost": 25.50,
        "Resale Value": 89.99,
        "Days in Process": 5,
        "Disposition": ""
    },
    {
        "SKU": "HG-3001",
        "Product Name": "Coffee Maker",
        "Category": "Home Goods",
        "Returned Qty": 1,
        "Condition": "Good",
        "Refurbishment Cost": 22.75,
        "Resale Value": 69.99,
        "Days in Process": 4,
        "Disposition": ""
    },
    {
        "SKU": "HG-3002",
        "Product Name": "Vacuum Cleaner",
        "Category": "Home Goods",
        "Returned Qty": 1,
        "Condition": "Fair",
        "Refurbishment Cost": 45.00,
        "Resale Value": 119.99,
        "Days in Process": 9,
        "Disposition": ""
    },
    {
        "SKU": "HG-3003",
        "Product Name": "Blender",
        "Category": "Home Goods",
        "Returned Qty": 1,
        "Condition": "Poor",
        "Refurbishment Cost": 18.50,
        "Resale Value": 24.99,
        "Days in Process": 7,
        "Disposition": ""
    },
    {
        "SKU": "HG-3004",
        "Product Name": "Toaster Oven",
        "Category": "Home Goods",
        "Returned Qty": 1,
        "Condition": "Like New",
        "Refurbishment Cost": 15.25,
        "Resale Value": 89.99,
        "Days in Process": 3,
        "Disposition": ""
    },
    {
        "SKU": "HG-3005",
        "Product Name": "Stand Mixer",
        "Category": "Home Goods",
        "Returned Qty": 1,
        "Condition": "Good",
        "Refurbishment Cost": 35.00,
        "Resale Value": 199.99,
        "Days in Process": 6,
        "Disposition": ""
    },
    {
        "SKU": "EL-1006",
        "Product Name": "Gaming Console",
        "Category": "Electronics",
        "Returned Qty": 1,
        "Condition": "Good",
        "Refurbishment Cost": 65.00,
        "Resale Value": 349.99,
        "Days in Process": 8,
        "Disposition": ""
    },
    {
        "SKU": "EL-1007",
        "Product Name": "Digital Camera",
        "Category": "Electronics",
        "Returned Qty": 1,
        "Condition": "Fair",
        "Refurbishment Cost": 48.50,
        "Resale Value": 159.99,
        "Days in Process": 12,
        "Disposition": ""
    },
    {
        "SKU": "AP-2005",
        "Product Name": "Formal Dress",
        "Category": "Apparel",
        "Returned Qty": 1,
        "Condition": "Like New",
        "Refurbishment Cost": 18.75,
        "Resale Value": 149.99,
        "Days in Process": 4,
        "Disposition": ""
    },
    {
        "SKU": "AP-2006",
        "Product Name": "Designer Sunglasses",
        "Category": "Apparel",
        "Returned Qty": 1,
        "Condition": "Good",
        "Refurbishment Cost": 12.00,
        "Resale Value": 99.99,
        "Days in Process": 3,
        "Disposition": ""
    },
    {
        "SKU": "HG-3006",
        "Product Name": "Air Purifier",
        "Category": "Home Goods",
        "Returned Qty": 1,
        "Condition": "Fair",
        "Refurbishment Cost": 38.25,
        "Resale Value": 129.99,
        "Days in Process": 7,
        "Disposition": ""
    },
    {
        "SKU": "HG-3007",
        "Product Name": "Robot Vacuum",
        "Category": "Home Goods",
        "Returned Qty": 1,
        "Condition": "Good",
        "Refurbishment Cost": 75.00,
        "Resale Value": 299.99,
        "Days in Process": 9,
        "Disposition": ""
    },
    {
        "SKU": "EL-1008",
        "Product Name": "Wireless Earbuds",
        "Category": "Electronics",
        "Returned Qty": 1,
        "Condition": "Like New",
        "Refurbishment Cost": 10.50,
        "Resale Value": 79.99,
        "Days in Process": 2,
        "Disposition": ""
    },
    {
        "SKU": "EL-1009",
        "Product Name": "4K Monitor",
        "Category": "Electronics",
        "Returned Qty": 1,
        "Condition": "Good",
        "Refurbishment Cost": 85.00,
        "Resale Value": 399.99,
        "Days in Process": 11,
        "Disposition": ""
    },
    {
        "SKU": "EL-1010",
        "Product Name": "Laptop",
        "Category": "Electronics",
        "Returned Qty": 1,
        "Condition": "Fair",
        "Refurbishment Cost": 125.00,
        "Resale Value": 599.99,
        "Days in Process": 14,
        "Disposition": ""
    },
    {
        "SKU": "AP-2007",
        "Product Name": "Athletic Shorts",
        "Category": "Apparel",
        "Returned Qty": 1,
        "Condition": "Good",
        "Refurbishment Cost": 6.50,
        "Resale Value": 29.99,
        "Days in Process": 3,
        "Disposition": ""
    },
    {
        "SKU": "AP-2008",
        "Product Name": "Wool Sweater",
        "Category": "Apparel",
        "Returned Qty": 1,
        "Condition": "Fair",
        "Refurbishment Cost": 14.75,
        "Resale Value": 59.99,
        "Days in Process": 5,
        "Disposition": ""
    },
    {
        "SKU": "HG-3008",
        "Product Name": "Espresso Machine",
        "Category": "Home Goods",
        "Returned Qty": 1,
        "Condition": "Good",
        "Refurbishment Cost": 95.00,
        "Resale Value": 449.99,
        "Days in Process": 10,
        "Disposition": ""
    },
    {
        "SKU": "HG-3009",
        "Product Name": "Food Processor",
        "Category": "Home Goods",
        "Returned Qty": 1,
        "Condition": "Poor",
        "Refurbishment Cost": 35.50,
        "Resale Value": 49.99,
        "Days in Process": 8,
        "Disposition": ""
    },
    {
        "SKU": "HG-3010",
        "Product Name": "Microwave Oven",
        "Category": "Home Goods",
        "Returned Qty": 1,
        "Condition": "Fair",
        "Refurbishment Cost": 42.25,
        "Resale Value": 89.99,
        "Days in Process": 6,
        "Disposition": ""
    },
    {
        "SKU": "EL-1011",
        "Product Name": "Smart TV",
        "Category": "Electronics",
        "Returned Qty": 1,
        "Condition": "Good",
        "Refurbishment Cost": 115.00,
        "Resale Value": 649.99,
        "Days in Process": 15,
        "Disposition": ""
    },
    {
        "SKU": "EL-1012",
        "Product Name": "Portable Charger",
        "Category": "Electronics",
        "Returned Qty": 1,
        "Condition": "Like New",
        "Refurbishment Cost": 8.25,
        "Resale Value": 39.99,
        "Days in Process": 2,
        "Disposition": ""
    }
];
